apiVersion: v1
kind: ConfigMap

metadata:
  name: back-config-map
  namespace: back-ns
data:
  MONGO_CONN_STR: "mongodb://mongodb-service.db-ns.svc.cluster.local:27017?authenticationDatabase=admin"
  USE_DB_AUTH: "true"
  
